# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pet_adoption.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'pet_adoption.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12pet_adoption.proto\x12\x0bpetAdoption\"\x07\n\x05\x45mpty\"]\n\x03Pet\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06gender\x18\x03 \x01(\t\x12\x0b\n\x03\x61ge\x18\x04 \x01(\x05\x12\r\n\x05\x62reed\x18\x05 \x01(\t\x12\x10\n\x08location\x18\x06 \x01(\t\".\n\x0cPetsResponse\x12\x1e\n\x04pets\x18\x01 \x03(\x0b\x32\x10.petAdoption.Pet\"\x1d\n\x0cPetIdRequest\x12\r\n\x05petId\x18\x01 \x01(\x05\"#\n\x10\x41\x64optionResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\";\n\x10PetSearchRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\x32\x95\x02\n\x0bPetAdoption\x12\x38\n\x07GetPets\x12\x12.petAdoption.Empty\x1a\x19.petAdoption.PetsResponse\x12\x44\n\x08\x41\x64optPet\x12\x19.petAdoption.PetIdRequest\x1a\x1d.petAdoption.AdoptionResponse\x12>\n\x0bRegisterPet\x12\x10.petAdoption.Pet\x1a\x1d.petAdoption.AdoptionResponse\x12\x46\n\nSearchPets\x12\x1d.petAdoption.PetSearchRequest\x1a\x19.petAdoption.PetsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pet_adoption_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=35
  _globals['_EMPTY']._serialized_end=42
  _globals['_PET']._serialized_start=44
  _globals['_PET']._serialized_end=137
  _globals['_PETSRESPONSE']._serialized_start=139
  _globals['_PETSRESPONSE']._serialized_end=185
  _globals['_PETIDREQUEST']._serialized_start=187
  _globals['_PETIDREQUEST']._serialized_end=216
  _globals['_ADOPTIONRESPONSE']._serialized_start=218
  _globals['_ADOPTIONRESPONSE']._serialized_end=253
  _globals['_PETSEARCHREQUEST']._serialized_start=255
  _globals['_PETSEARCHREQUEST']._serialized_end=314
  _globals['_PETADOPTION']._serialized_start=317
  _globals['_PETADOPTION']._serialized_end=594
# @@protoc_insertion_point(module_scope)
